name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 1
        run: |
          mkdir build
          cd build
          curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo -E apt-add-repository -y 'ppa:ubuntu-toolchain-r/test'
          sudo add-apt-repository ppa:mhier/libboost-latest
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get install --force-yes \
              cmake \
              clang \
              libboost-dev \
              libboost-filesystem-dev \
              libboost-locale-dev \
              libssl-dev \
              libpng-dev \
              libjpeg-dev \
              libwebp-dev \
              autopoint \
              bison \
              flex \
              libtool-bin \
              libltdl-dev \
              lzip \
              gperf \
              intltool
          export CMAKE_CXX_COMPILER=clang++
          git clone https://github.com/mxe/mxe.git
      - name: 2
        run: |
          cd build
          cd mxe
          MXE_GCC_THREADS=posix \
           MXE_PLUGIN_DIRS=plugins/gcc6/ \
           make libiconv zlib libpng jpeg boost openssl libwebp -j8 JOBS=8
          ls -R
      - name: 3
        run: |
           mkdir build-mxe
           cd build-mxe
           ../build/mxe/usr/bin/i686-w64-mingw32.static-cmake ..
           make -j8
      - name: Check exists
        run: |
          ls -R
          file build/arc_unpacker
