name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 1
        run: |
          curl -sSL 'https://apt.llvm.org/llvm-snapshot.gpg.key' | sudo -E apt-key add -
          sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 3D5919B448457EE0 
          echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.8 main' | sudo tee -a /etc/apt/sources.list > /dev/null
          sudo -E apt-add-repository -y 'ppa:ubuntu-toolchain-r/test'
          sudo -E apt-add-repository -y 'ppa:kalakris/cmake'
          sudo -E apt-add-repository -y "ppa:boost-latest/ppa"
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get install --force-yes \
              cmake \
              clang-3.8 \
              libboost1.55-dev \
              libboost-filesystem1.55-dev \
              libboost-locale1.55-dev \
              libssl-dev \
              libpng-dev \
              libjpeg-dev
          export CMAKE_CXX_COMPILER=clang++-3.8
      - name: 2
        run: cmake -DCMAKE_BUILD_TYPE=release # for debug build, change to debug
      - name: 3
        run: make -j8
