name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 3
        run: cmake -DCMAKE_BUILD_TYPE=release .. # for debug build, change to debug
      - name: 4
        run: make -j8
