name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
          - name: 1
            run:  mkdir build
            run: cd build
            run: cmake -DCMAKE_BUILD_TYPE=release .. # for debug build, change to debug
            run: make -j8
