name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 1
        run: |
          curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo -E apt-add-repository -y 'ppa:ubuntu-toolchain-r/test'
          sudo add-apt-repository ppa:mhier/libboost-latest
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get install --force-yes \
              cmake \
              clang \
              libboost-dev \
              libboost-filesystem-dev \
              libboost-locale-dev \
              libssl-dev \
              libpng-dev \
              libjpeg-dev
          export CMAKE_CXX_COMPILER=clang++
      - name: 2
        run: cmake -DCMAKE_BUILD_TYPE=release # for debug build, change to debug
      - name: 3
        run: make -j8
